version: 0.0
os: linux
files:
  - source: appsettings.json
    destination: /webapps/ImageColourSwap
  - source: AWSSDK.Core.dll
    destination: /webapps/ImageColourSwap
  - source: AWSSDK.S3.dll
    destination: /webapps/ImageColourSwap
  - source: SixLabors.ImageSharp.dll
    destination: /webapps/ImageColourSwap
  - source: web.config
    destination: /webapps/ImageColourSwap
  - source: Web.deps.json
    destination: /webapps/ImageColourSwap
  - source: Web.dll
    destination: /webapps/ImageColourSwap
  - source: Web.runtimeconfig.json
    destination: /webapps/ImageColourSwap/wwwroot
  - source: wwwroot/
    destination: /webapps/ImageColourSwap/wwwroot
file_exists_behavior: OVERWRITE
hooks:
  ApplicationStart:
    - location: Scripts/run.sh
      timeout: 30
