version: 0.0
os: linux
files:
  - source: Deployment/Amazon.AspNetCore.Identity.Cognito.dll
    destination: /home/ec2-user/ImageColourSwap
  - source: Deployment/Amazon.Extensions.CognitoAuthentication.dll
    destination: /home/ec2-user/ImageColourSwap
  - source: Deployment/Amazon.Extensions.Configuration.SystemsManager.dll
    destination: /home/ec2-user/ImageColourSwap
  - source: Deployment/appsettings.json
    destination: /home/ec2-user/ImageColourSwap
  - source: Deployment/AWS.Logger.AspNetCore.dll
    destination: /home/ec2-user/ImageColourSwap
  - source: Deployment/AWS.Logger.Core.dll
    destination: /home/ec2-user/ImageColourSwap
  - source: Deployment/AWSSDK.AppConfigData.dll
    destination: /home/ec2-user/ImageColourSwap
  - source: Deployment/AWSSDK.CloudWatchLogs.dll
    destination: /home/ec2-user/ImageColourSwap
  - source: Deployment/AWSSDK.CognitoIdentity.dll 
    destination: /home/ec2-user/ImageColourSwap
  - source: Deployment/AWSSDK.CognitoIdentityProvider.dll
    destination: /home/ec2-user/ImageColourSwap
  - source: Deployment/AWSSDK.Core.dll
    destination: /home/ec2-user/ImageColourSwap
  - source: Deployment/AWSSDK.DynamoDBv2.dll
    destination: /home/ec2-user/ImageColourSwap
  - source: Deployment/AWSSDK.Extensions.NETCore.Setup.dll
    destination: /home/ec2-user/ImageColourSwap
  - source: Deployment/AWSSDK.S3.dll
    destination: /home/ec2-user/ImageColourSwap
  - source: Deployment/AWSSDK.SecurityToken.dll
    destination: /home/ec2-user/ImageColourSwap
  - source: Deployment/AWSSDK.SimpleSystemsManagement.dll
    destination: /home/ec2-user/ImageColourSwap
  - source: Deployment/SixLabors.ImageSharp.dll
    destination: /home/ec2-user/ImageColourSwap
  - source: Deployment/web.config
    destination: /home/ec2-user/ImageColourSwap
  - source: Deployment/Web.deps.json
    destination: /home/ec2-user/ImageColourSwap
  - source: Deployment/Web.dll
    destination: /home/ec2-user/ImageColourSwap
  - source: Deployment/Web.runtimeconfig.json
    destination: /home/ec2-user/ImageColourSwap
  - source: Deployment/wwwroot/
    destination: /home/ec2-user/ImageColourSwap/wwwroot
  - source: Deployment/ImageColourSwap.service
    destination: /home/ec2-user/ImageColourSwap
  - source: Deployment/ImageColourSwap.conf
    destination: /home/ec2-user/ImageColourSwap
  - source: Deployment/ImageHelpers.dll
    destination: /home/ec2-user/ImageColourSwap
file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: Deployment/CodeDeployScripts/ApplicationStop.sh
  ApplicationStart:
    - location: Deployment/CodeDeployScripts/ApplicationRun.sh
      timeout: 60
