version: 0.0
os: linux
files:
  - source: appsettings.json
    destination: /home/ec2-user/ImageColourSwap
  - source: AWS.Logger.AspNetCore.dll
    destination: /home/ec2-user/ImageColourSwap
  - source: AWS.Logger.Core.dll
    destination: /home/ec2-user/ImageColourSwap
  - source: AWSSDK.Core.dll
    destination: /home/ec2-user/ImageColourSwap
  - source: AWSSDK.DynamoDBv2.dll
    destination: /home/ec2-user/ImageColourSwap
  - source: AWSSDK.S3.dll
    destination: /home/ec2-user/ImageColourSwap
  - source: SixLabors.ImageSharp.dll
    destination: /home/ec2-user/ImageColourSwap
  - source: web.config
    destination: /home/ec2-user/ImageColourSwap
  - source: Web.deps.json
    destination: /home/ec2-user/ImageColourSwap
  - source: Web.dll
    destination: /home/ec2-user/ImageColourSwap
  - source: Web.runtimeconfig.json
    destination: /home/ec2-user/ImageColourSwap
  - source: wwwroot/
    destination: /home/ec2-user/ImageColourSwap/wwwroot
  - source: ImageColourSwap.service
    destination: /home/ec2-user/ImageColourSwap
  - source: ImageColourSwap.conf
    destination: /home/ec2-user/ImageColourSwap
  - source: "Image Colour Swap.dll"
    destination: /home/ec2-user/ImageColourSwap
file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: Scripts/ApplicationStop.sh
  AfterInstall:
    - location: Scripts/AfterInstall.sh
  ApplicationStart:
    - location: Scripts/ApplicationRun.sh
      timeout: 60
