version: 0.2

env:
  parameter-store:
    CODE_ARTIFACT_DOMAIN: /CodeBuild/CodeArtifact/Domain
    CODE_ARTIFACT_DOMAIN_OWNER: /CodeBuild/CodeArtifact/DomainOwner
    CODE_ARTIFACT_REPOSITORY: /CodeBuild/CodeArtifact/Repository

phases:
  install:
    runtime-versions:
      dotnet: latest
    commands:
      - /usr/local/bin/dotnet-install.sh --channel LTS
      - dotnet tool install -g AWS.CodeArtifact.NuGet.CredentialProvider
      - dotnet codeartifact-creds install
  pre_build:
    commands:
      - dotnet nuget add source -n codeartifact $(aws codeartifact get-repository-endpoint 
        --domain $CODE_ARTIFACT_DOMAIN 
        --domain-owner $CODE_ARTIFACT_DOMAIN_OWNER 
        --repository $CODE_ARTIFACT_REPOSITORY 
        --format nuget 
        --query repositoryEndpoint 
        --output text)"v3/index.json"
      - dotnet restore Code/Web.csproj
  build:
    commands:
      dotnet build Code/Web.csproj
  post_build:
    commands:
      - ./buildandpackage.sh
      - dotnet pack --no-build --no-restore Code/Web.csproj /p:OutputPath=Site -o Code/Nuget
      - dotnet nuget push Code/Nuget/*.nupkg -s codeartifact --skip-duplicate
      - aws s3 cp Code/Nuget/ s3://imagecolourswap/ImageColourSwapWeb/ --recursive --exclude "*" --include "*.nupkg"
      - source_version=$(aws s3api list-objects --bucket imagecolourswap --prefix ImageColourSwapWeb/ --query 'sort_by(Contents, &LastModified)[-1].Key' --output text)
      - deployment_id=$(aws deploy create-deployment --application-name ImageColourSwapWeb --deployment-group Integration --s3-location bucket=imagecolourswap,bundleType=zip,key=$source_version --query deploymentId | tr -d '"')
      - aws deploy wait deployment-successful --deployment-id $deployment_id

artifacts:
  files:
    - '*.nupkg'
  name: 'ImageColourSwapWeb'
  base-directory: 'Code/Nuget'