version: 0.2

phases:
  install:
        commands:
      /usr/local/bin/dotnet-install.sh --channel LTS
  pre_build:
    commands:
      dotnet restore Web.csproj
  build:
    commands:
      dotnet build Web.csproj
  post_build:
    commands:
      ./buildandpackage.sh
artifacts:
  files:
    - '**/*'
  name: 'ImageColourSwapWeb'
  base-directory: 'Site'